// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZBYNcEUFP8RFleXoqVkq47XF8-ohmPtg',
    appId: '1:470342203389:web:11f2fa6ff8f5c277fe0b94',
    messagingSenderId: '470342203389',
    projectId: 'e-commerce-app-169b2',
    authDomain: 'e-commerce-app-169b2.firebaseapp.com',
    storageBucket: 'e-commerce-app-169b2.firebasestorage.app',
    measurementId: 'G-M15V4VYSP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9RdmjZGfenpEULXx1MI8RoO1Zk6KMKi0',
    appId: '1:507932806086:android:56912a0d401860962540c7',
    messagingSenderId: '507932806086',
    projectId: 'nuevent2025',
    storageBucket: 'nuevent2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQiRJcJYQovP1hPdzKe4-KJxZRRZN0MkI',
    appId: '1:470342203389:ios:f4f5340c464de426fe0b94',
    messagingSenderId: '470342203389',
    projectId: 'e-commerce-app-169b2',
    storageBucket: 'e-commerce-app-169b2.firebasestorage.app',
    androidClientId:
        '470342203389-2c182grbirdmmlvvcsqm7vsk20fmpbak.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQiRJcJYQovP1hPdzKe4-KJxZRRZN0MkI',
    appId: '1:470342203389:ios:f4f5340c464de426fe0b94',
    messagingSenderId: '470342203389',
    projectId: 'e-commerce-app-169b2',
    storageBucket: 'e-commerce-app-169b2.firebasestorage.app',
    androidClientId:
        '470342203389-2c182grbirdmmlvvcsqm7vsk20fmpbak.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZBYNcEUFP8RFleXoqVkq47XF8-ohmPtg',
    appId: '1:470342203389:web:4e4a7fc425450ad2fe0b94',
    messagingSenderId: '470342203389',
    projectId: 'e-commerce-app-169b2',
    authDomain: 'e-commerce-app-169b2.firebaseapp.com',
    storageBucket: 'e-commerce-app-169b2.firebasestorage.app',
    measurementId: 'G-1DNP0JWWJC',
  );
}
